### ISSUE TITLE
incorrect package name of docs 'getting started' page[BUG]

### ISSUE THREAD

**Issue by ramiel1999** [TheWidlarzGroup/react-native-notificated#139]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**

The [docs](https://thewidlarzgroup.github.io/react-native-notificated/docs/intro/) mention to install using
`yarn add react-native-notificaitons`
which actually should be
`yarn add react-native-notificated`

**Comment by danielmark0116** [comment]
🙉 you're right! thanks for the catch!
