### ISSUE TITLE
[BUG] notify or useNotifications imports from package in monorepo doesn't work 

### ISSUE THREAD

**Issue by jesuscovam** [TheWidlarzGroup/react-native-notificated#159]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**
In a monorepo, I need to prop drill the notify function from the navigator (on the app) to the Screen (from a package in the monorepo) that I shared between 2 apps.

From the Screen in the package, direct import of notify or useNotifications doesn't work

**To Reproduce**
1. import notify or useNotifications from a component or screen from a package in a monorepo

**Expected behavior**
the display of a the notification when the notify function is called

**Possible Solution**
Im sharing the notify function as a route params through react-navigation

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - Simulator: [Yes]
 - OS: [iOS 14.5]

**Additional context**
running on the Expo Go App.

**Comment by woodrejs** [comment]
Thank you for letting us know about this Issue. We will look at it as soon as possible 😃

**Comment by woodrejs** [comment]
@jesuscovam  Can you show logs for errors that you receive?

**Comment by mateki0** [comment]
Closing because we don't get reply for a long time. Please reopen if it's still an issue

**Comment by PdoubleU** [comment]
Hi @jesuscovam 👋 , how's going?

It's been quite a while since you opened this issue. I was just wondering, have you been using react-native-notificated recently? Did that bug pop up again? 🤔
