### ISSUE TITLE
[BUG] When working with a modal, the toast is displayed behind the modal

### ISSUE THREAD

**Issue by Nziranziza** [TheWidlarzGroup/react-native-notificated#211]
**Prerequisites**
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**
When working with a modal, the toast message intended to be displayed sometimes appears behind the modal, creating difficulty in reading its content

**To Reproduce**
1. Set up a modal along with a button that triggers the opening of a toast.
2. Click the button to open the toast within the modal.
3. Take note of the toast's display and observe its appearance.

**Expected behavior**
When working with a modal, it is preferable to display the toast message on top of the modal for better visibility and readability.

**Possible Solution**
One potential solution would be to incorporate an additional NotificationProvider within the modal. However, it is important to note that having multiple NotificationProviders could result in multiple toasts being displayed. To address this, it is crucial to ensure that only a single toast is shown despite the presence of multiple NotificationProviders. If this can be achieved, adding a NotificationProvider inside a modal would be a viable approach.

**Screenshots**
<img width="472" alt="image" src="https://github.com/TheWidlarzGroup/react-native-notificated/assets/37615728/1281c9aa-39b1-447d-acc5-23c7fd82f534">

**Smartphone (please complete the following information):**
 - Device: Iphone 14 pro
 - Simulator: yes
 - OS: iOS 16.2

**Additional context**
N/A

**Comment by PdoubleU** [comment]
Hi @Nziranziza,

Thank you for trying out react-native-notificated and bringing this bug to our attention.

I was wondering if you had an opportunity to try the latest version that addresses your issue. 🤔

Do you have any thoughts about our library? Is there something we can work on improving?

**Comment by Nziranziza** [comment]
> Hi @Nziranziza,
> 
> Thank you for trying out react-native-notificated and bringing this bug to our attention.
> 
> I was wondering if you had an opportunity to try the latest version that addresses your issue. 🤔
> 
> Do you have any thoughts about our library? Is there something we can work on improving?

Hello @PdoubleU thank you very much for working on this, I tested it and it is working as expected
