### ISSUE TITLE
[BUG] After upgrade version from 0.1.0 to newer, expo web crashes

### ISSUE THREAD

**Issue by micbaumr** [TheWidlarzGroup/react-native-notificated#249]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**
I'm using expo to build android, ios and web app. After upgrading react-native-notificated from 0.1.0 version to 0.1.1 or higher I got error :

```
Uncaught Error: Your web project is importing a module from 'react-native' instead of 'react-native-web'. Learn more: https://expo.fyi/fb-batched-bridge-config-web
    at get (Expo.fx.web.tsx:12:1)
    at ./node_modules/react-native/Libraries/BatchedBridge/NativeModules.js (NativeModules.js:181:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js (TurboModuleRegistry.js:15:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/react-native/Libraries/Components/StatusBar/NativeStatusBarManagerIOS.js (NativeModules.js:210:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```
**To Reproduce**
1. Run expo project with react-native-notificated version 0.1.0
2. Bump react-native-notificated to version 0.1.1
3. See error

**Expected behavior**
Running in web browser without an error

**Screenshots**
<img width="1295" alt="Screenshot 2023-12-20 at 12 57 29" src="https://github.com/TheWidlarzGroup/react-native-notificated/assets/60507270/8ac32fc9-159b-4726-b179-3e20714d17f1">

**Smartphone (please complete the following information):**
 - Device: Macbook
 - OS: MacOS
 - Browser: Google Chrome
 - Version: 120.0.6099.109

**Comment by PdoubleU** [comment]
Hey @micbaumr, thanks for bringing this error to our attention. We'll work on fixing it as soon as possible and get back to you with an update.

**Comment by mtzfactory** [comment]
Hi! I'm facing the very same problem. I'm using Expo with `expo-router`

![Screenshot 2024-05-15 at 15 21 31](https://github.com/TheWidlarzGroup/react-native-notificated/assets/200234/a7aa12ca-daf4-4bfc-a16a-951e6506e0d9)

This is my `package.json` file:

```
    "expo": "^49.0.0",
    "expo-blur": "~12.4.1",
    "expo-clipboard": "~4.3.0",
    "expo-constants": "~14.4.2",
    "expo-device": "~5.4.0",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-localization": "~14.3.0",
    "expo-router": "~2.0.0",
    "expo-status-bar": "~1.6.0",
    ...
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-notificated": "^0.1.5",
    "react-native-reanimated": "~3.3.0",
    ...
```

@PdoubleU have you had time to review this problem?

@micbaumr did you find a solution?

Thank you!

**Comment by danielmark0116** [comment]
here is a PR with a fix:

https://github.com/TheWidlarzGroup/react-native-notificated/pull/266

It's going to be released soon but before that, you can always try to install directly from the branch for the time being

Let me know if issue is gone! :)
