### ISSUE TITLE
[BUG] In some project's configurations notification positioning left/right doesn't work

### ISSUE THREAD

**Issue by PdoubleU** [TheWidlarzGroup/react-native-notificated#252]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**
The right and left seem not to work in some apps (looks like some layout styles interfere with the notification styles)

**To Reproduce**
1. Create fresh React Native app 
2. Install package react-native-notificated (latest version)
3. Initialize notifications component with default (notification should be centered)
4. Add notification to the event in the app (i.e. on button press)
5. Notification, despite default styles is located on the left (without any space from the corner of the screen)

**Expected behavior**
By default notification should be centered on the top

**Possible Solution**
Seems like style issue. 

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: n/a
 - Simulator: ios/android
 - OS:  n/a
 - Version n/a

**Additional context**

**Comment by sanduluca** [comment]
Same issue. I see a PR open and tested it. It worked for me. Hope it will be released soon
