### ISSUE TITLE
How to unit test the toast?

### ISSUE THREAD

**Issue by MarlonAEC** [TheWidlarzGroup/react-native-notificated#267]
Is it possible to unit-test this library? Like adding a full integration test to verify the toast has been launched or maybe a way to mock the toast to be used inside a Jest unit test? If so, is it possible to add more info about it in the docs

**Comment by PdoubleU** [comment]
Hey @MarlonAEC .  The fastest way to test toasts in your project is by using `*ByText` [query](https://callstack.github.io/react-native-testing-library/docs/api/queries#by-text).
