### ISSUE TITLE
Notification is hidden behind modal

### ISSUE THREAD

**Issue by wilkinsonj** [TheWidlarzGroup/react-native-notificated#273]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Describe the bug**
When I display a notification whilst a user is viewing a modal (react-native-modal) it is hidden behind the modal

**To Reproduce**
1. Add a react-native-modal in view
2. Raise a notification
3. Don't see notification

**Expected behavior**
Ideally the notification would sit on top of everything else

**Possible Solution**
I know that this is tricky because of the way RN handles modals (above everything else) but I believe other libraries have achieved it.

**Comment by quannh-torus** [comment]
hi @wilkinsonj 
I found an example in the[documentation](https://thewidlarzgroup.github.io/react-native-notificated/docs/intro/examples/notification-in-modal-example). Do you find it helpful?

**Comment by PdoubleU** [comment]
@wilkinsonj I hope you solved it. For now I close this issue. Package is handling modals and notifications, please see [ocumentation](https://thewidlarzgroup.github.io/react-native-notificated/docs/intro/examples/notification-in-modal-example). If there is a problem with notification in modal, feel free to reopen this issue.
