### ISSUE TITLE
extend remove method

### ISSUE THREAD

**Issue by EuSet** [TheWidlarzGroup/react-native-notificated#275]
would be very useful in some cases remove several/all notifies from the queue

**Comment by PdoubleU** [comment]
Hi @EuSet , thanks for sharing your thoughts. Your proposal is very interesting. Also feel free to play with the package and add desired changes on your own - this is open source project, and the community can shape it :) I would be happy to review your PR ❤️

**Comment by EuSet** [comment]
@PdoubleU thank you for answering I'll consider PR but close it so far)
