### ISSUE TITLE
[IMPROVEMENT] Initialize default notification instance without a need to provide any config

### ISSUE THREAD

**Issue by danielmark0116** [TheWidlarzGroup/react-native-notificated#83]
**Is your feature request related to a problem? Please describe.**
As a developer using the library, I want to quickly instantiate the library without a need to pass in the config. Although this can partialy be done now, the API requires to pass an empty object as argument.

**Describe the solution you'd like**
No need to pass an empty `{}` to `createNotification` initializer.

**Describe alternatives you've considered**
An alternative would be to use the `{}`, which I guess we do not want 🤔 

**Additional context**
...

---

Instead of:
```typescript
const {} = createNotifications({})
```

this:
```typescript
const {} = createNotifications()
```

**Comment by mjaskowska** [comment]
Feature implemented.
