### ISSUE TITLE
[DOCS] GestureHandlerRootView hint for rn-gesture-handler v2

### ISSUE THREAD

**Issue by danielmark0116** [TheWidlarzGroup/react-native-notificated#99]
Given that the library is based on `react-native-gesture-handler`, docs should also have a hint on the v2 of the gesture handler -> for android, the `NotificationsProvider` should be placed within the `GestureHandlerRootView`

**Comment by mjaskowska** [comment]
Closing this issue. Documentation directs to `react-native-gesture-handler` official docs with all installation guidelines.
